name: "SAST-action"
author: ivankuchin
description: "GitHub Action examines C/C++ source code and reports possible security weaknesses (“flaws”) sorted by risk level."

inputs:
  GITHUB_TOKEN:
    description: "GITHUB_TOKEN (automatically assinged by GitHub)"
    required: true

  DATAONLY:
    description: "Don’t display the header and footer."
    default: "true"
    required: false

  SOURCE_CODE:
    description: "Source code folder or file to check."
    default: "./"
    required: false

runs:
  using: "docker"
  image: "Dockerfile"

branding:
  icon: "life-buoy"
  color: "blue"
